In-memory write caching
EdgeApp/memlet pull request #7
Opened 2021-05-04 01:42 UTC by samholmes

2021-05-11 22:03 UTC, samholmes commented on src/index.ts
> +      const dataString = JSON.stringify(data)
Consider fast-json-stringify for optimization

2021-05-11 22:44 UTC, samholmes commented on src/index.ts
> +  }
Store global `timeoutId`. Only start `setTimeout` if `timeoutId == null`. Set `timeoutId = null` if `memoryOnlyFileQueue` is empty or on caught error.

2021-05-11 23:00 UTC, samholmes commented on src/index.ts
> +  memoryOnlyFileQueue: makeFileQueue()
Perhaps, generalize `FileQueue` to `Queue` which works on a generic type `T extends {lastTouchedTimestamp: number, key: string}`

2021-05-27 04:39 UTC, thehobbit85 requested changes
See comments.

2021-05-27 04:39 UTC, thehobbit85 commented on src/index.ts
> +  let _nextFlushEvent: Promise<void> | undefined
no reason to use the underscore convention since you don't even expose this param.

2021-05-27 04:39 UTC, thehobbit85 commented on src/index.ts
> +    if (_nextFlushEvent != null) {
Can you please "one liner" it? ;)

2021-05-27 04:39 UTC, thehobbit85 commented on src/queue.ts
> +  const timestampMap: Map<string, number> = new Map()
Unfortunately we can't use `Map` in any of the plugins or the the libs that are being used them.
It has some unpredictable bugs after being transpiled in the App.

2021-05-28 04:37 UTC, thehobbit85 approved these changes

2021-05-28 04:38 UTC, merged